### ISSUE TITLE
Use Hypothes.is instead of Disqus as annotation and conversation layer.

### ISSUE THREAD

**Issue by almereyda** [scripting/myWordEditor#3]
Disqus is already implemented in a sidefold (on the left side) as a third-party service providing a discussion component to the essays.

Instead @hypothesis offers a [silo-free](http://littlecardeditor.com/users/davewiner/cards/2015/03/09/letsGetBus185.html) free and open source infrastructure (on the right side) for a web annotation and conversation layer.

Trapped into this when accidentally ending up at http://myword.io/users/lmereyda/essays/001.html#

Greetings from Berlin.

**Comment by scripting** [comment]
Thanks for the suggestion and sorry to take so long to respond (I have to set things up so I get automatic notification). 

Right now this product isn't in active development. Further I have never done an integration of hypothesis, I haven't even used it, so it's very hard to evaluate the request. However I will think about it. I am closing this issue for now. Again, thanks for the suggestion! 👍
